In [1]:
import pandas as pd

data = {
    'Name': ['John', 'Mary', 'Bob', 'Sarah', 'Tom', 'Lisa'],
    'Department': ['IT', 'Marketing', 'Sales', 'IT', 'Finance', 'Marketing'],
    'Age': [30, 40, 25, 35, 45, 28],
    'Gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female'],
    'Salary': [50000, 60000, 45000, 55000, 70000, 55000],
    'Experience': [3, 7, 2, 5, 10, 4]
}

employee_df = pd.DataFrame(data)

In [2]:
employee_df.iloc[:3]

   Name Department  Age  Gender  Salary  Experience
0  John         IT   30    Male   50000           3
1  Mary  Marketing   40  Female   60000           7
2   Bob      Sales   25    Male   45000           2

In [3]:
employee_df.loc[employee_df['Department'] == 'Marketing']

   Name Department  Age  Gender  Salary  Experience
1  Mary  Marketing   40  Female   60000           7
5  Lisa  Marketing   28  Female   55000           4

In [4]:
employee_df.iloc[:4, [2, 3]]

   Age  Gender
0   30    Male
1   40  Female
2   25    Male
3   35  Female

In [5]:
employee_df.loc[employee_df['Gender'] == 'Male', ['Salary', 'Experience']]

   Salary  Experience
0   50000           3
2   45000           2
4   70000          10